title: Arthur Bastos 
logo: "/images/Perfil.jpg"
description: > 
  <A href="/about.html">About Me</a>
  <br>
  <A href="https://arthursb.github.io/">Portfolio</a>
  <br>
  <a href="/resume.pdf">Resume</a> 
  <br>
  <a href="https://www.linkedin.com/in/arthursbastos/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
